// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace RawDataExplorers.Data.Pokemon
{
    public class Xml
    {

        [JsonProperty("@version")]
        public string Version { get; set; }
    }

    public class English
    {

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Category")]
        public string Category { get; set; }
    }

    public class Strings
    {

        [JsonProperty("English")]
        public English English { get; set; }
    }

    public class EvolutionReq
    {

        [JsonProperty("PreEvoIndex")]
        public string PreEvoIndex { get; set; }

        [JsonProperty("Method")]
        public string Method { get; set; }

        [JsonProperty("Param1")]
        public string Param1 { get; set; }

        [JsonProperty("Param2")]
        public string Param2 { get; set; }
    }

    public class BaseStats
    {

        [JsonProperty("HP")]
        public string HP { get; set; }

        [JsonProperty("Attack")]
        public string Attack { get; set; }

        [JsonProperty("SpAttack")]
        public string SpAttack { get; set; }

        [JsonProperty("Defense")]
        public string Defense { get; set; }

        [JsonProperty("SpDefense")]
        public string SpDefense { get; set; }
    }

    public class ExclusiveItems
    {

        [JsonProperty("ItemID")]
        public string[] ItemID { get; set; }
    }

    public class GenderedEntity
    {

        [JsonProperty("PokeID")]
        public string PokeID { get; set; }

        [JsonProperty("Unk31")]
        public string Unk31 { get; set; }

        [JsonProperty("PokedexNumber")]
        public string PokedexNumber { get; set; }

        [JsonProperty("Unk1")]
        public string Unk1 { get; set; }

        [JsonProperty("EvolutionReq")]
        public EvolutionReq EvolutionReq { get; set; }

        [JsonProperty("SpriteIndex")]
        public string SpriteIndex { get; set; }

        [JsonProperty("Gender")]
        public string Gender { get; set; }

        [JsonProperty("BodySize")]
        public string BodySize { get; set; }

        [JsonProperty("PrimaryType")]
        public string PrimaryType { get; set; }

        [JsonProperty("SecondaryType")]
        public string SecondaryType { get; set; }

        [JsonProperty("MovementType")]
        public string MovementType { get; set; }

        [JsonProperty("IQGroup")]
        public string IQGroup { get; set; }

        [JsonProperty("PrimaryAbility")]
        public string PrimaryAbility { get; set; }

        [JsonProperty("SecondaryAbility")]
        public string SecondaryAbility { get; set; }

        [JsonProperty("Bitfield")]
        public string Bitfield { get; set; }

        [JsonProperty("ExpYield")]
        public string ExpYield { get; set; }

        [JsonProperty("RecruitRate1")]
        public string RecruitRate1 { get; set; }

        [JsonProperty("RecruitRate2")]
        public string RecruitRate2 { get; set; }

        [JsonProperty("BaseStats")]
        public BaseStats BaseStats { get; set; }

        [JsonProperty("Weight")]
        public string Weight { get; set; }

        [JsonProperty("Size")]
        public string Size { get; set; }

        [JsonProperty("Unk17")]
        public string Unk17 { get; set; }

        [JsonProperty("Unk18")]
        public string Unk18 { get; set; }

        [JsonProperty("Unk19")]
        public string Unk19 { get; set; }

        [JsonProperty("Unk20")]
        public string Unk20 { get; set; }

        [JsonProperty("Unk21")]
        public string Unk21 { get; set; }

        [JsonProperty("BasePokemonIndex")]
        public string BasePokemonIndex { get; set; }

        [JsonProperty("ExclusiveItems")]
        public ExclusiveItems ExclusiveItems { get; set; }

        [JsonProperty("Unk27")]
        public string Unk27 { get; set; }

        [JsonProperty("Unk28")]
        public string Unk28 { get; set; }

        [JsonProperty("Unk29")]
        public string Unk29 { get; set; }

        [JsonProperty("Unk30")]
        public string Unk30 { get; set; }
    }

    public class Learn
    {

        [JsonProperty("Level")]
        public int Level { get; set; }

        [JsonProperty("MoveID")]
        public string MoveID { get; set; }
    }

    public class LevelUpMoves
    {

        [JsonProperty("Learn")]
        public Learn[] Learn { get; set; }
    }

    public class EggMoves
    {

        [JsonProperty("MoveID")]
        public string[] MoveID { get; set; }
    }

    public class HmTmMoves
    {

        [JsonProperty("MoveID")]
        public string[] MoveID { get; set; }
    }

    public class Moveset
    {

        [JsonProperty("#comment")]
        public object[] Comment { get; set; }

        [JsonProperty("LevelUpMoves")]
        public LevelUpMoves LevelUpMoves { get; set; }

        [JsonProperty("EggMoves")]
        public EggMoves EggMoves { get; set; }

        [JsonProperty("HmTmMoves")]
        public HmTmMoves HmTmMoves { get; set; }
    }

    public class Level
    {

        [JsonProperty("RequiredExp")]
        public string RequiredExp { get; set; }

        [JsonProperty("HP")]
        public string HP { get; set; }

        [JsonProperty("Attack")]
        public string Attack { get; set; }

        [JsonProperty("SpAttack")]
        public string SpAttack { get; set; }

        [JsonProperty("Defense")]
        public string Defense { get; set; }

        [JsonProperty("SpDefense")]
        public string SpDefense { get; set; }
    }

    public class StatsGrowth
    {

        [JsonProperty("#comment")]
        public object[] Comment { get; set; }

        [JsonProperty("Level")]
        public Level[] Level { get; set; }
    }

    public class Pokemon2
    {

        [JsonProperty("@gameVersion")]
        public string GameVersion { get; set; }

        [JsonProperty("#comment")]
        public object[] Comment { get; set; }

        [JsonProperty("Strings")]
        public Strings Strings { get; set; }

        [JsonProperty("GenderedEntity")]
        public GenderedEntity[] GenderedEntity { get; set; }

        [JsonProperty("Moveset")]
        public Moveset[] Moveset { get; set; }

        [JsonProperty("StatsGrowth")]
        public StatsGrowth StatsGrowth { get; set; }
    }

    public class Pokemon
    {

        [JsonProperty("?xml")]
        public Xml Xml { get; set; }

        [JsonProperty("Pokemon")]
        public Pokemon2 Pokemon2 { get; set; }
    }

}
