#!/bin/bash

echo Pulling repository...
git pull
echo Changing Directory...
cd DashingWanderer
echo Copying config.json to binary directory...
cp config.json bin/Debug/netcoreapp2.0/config.json
echo Restoring Nuget Packages...
dotnet restore
echo Running Dashing Wanderer...
dotnet run